name: Pipeline

on:
  pull_request:
  push:
    branches:
      - develop
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly run for security scans

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.7
      
      - name: Install Dependencies
        run: flutter pub get
      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Format
        run: make format

      - name: Analyze
        run: make analyze

      - name: Test
        run: make test

      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v2.3.2
        with:
          # Scan the lockfile
          scan-args: |-
            --lockfile=pubspec.lock
